name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
 #LOGIN: ${{ secrets.DOCKER_LOGIN }}
 #NAME: ${{ secrets.DOCKER_NAME }}
 VER: ${{ (date +%s) }}
 
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to docker.io
      run:  echo ${{ secrets.DOCKER_PWD }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag rmulyukov/nginxtest:${{VER}}
     # ${GITHUB_REF:11}
    - name: Push image to docker.io
      run: docker push rmulyukov/nginxtest:${{VER}}
  
